version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  products-service:
    build: ./products-service
    ports:
      - "8080:8080"
    depends_on:
      - db

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  pgdata:
